### ISSUE TITLE
Second example seems weird

### ISSUE THREAD

**Issue by haarg** [xsawyerx/perl-critic-policy-variables-prohibitlooponhash#1]
This line:

    action() for %{ keys $hash{'stuff'} ? $hash{'stuff'} : {} }; # ok

seems odd.  The ternary would seem to rely on auto-deref, as well as being pointless.  Is that actually the type of expression you meant?

**Comment by xsawyerx** [comment]
Whoops. This was supposed to be a deref. I'll fix the docs. Thanks!

**Comment by xsawyerx** [comment]
Fixed in new release.
